
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class AddInstanceItemSignal : ServerConfigableSignal
{
    public AddInstanceItemSignal(ByteBuf _buf)  : base(_buf) 
    {
        ConfigID = _buf.ReadInt();
        Level = _buf.ReadInt();
    }

    public static AddInstanceItemSignal DeserializeAddInstanceItemSignal(ByteBuf _buf)
    {
        return new AddInstanceItemSignal(_buf);
    }

    public readonly int ConfigID;
    public readonly int Level;
   
    public const int __ID__ = 2111140977;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ConfigID:" + ConfigID + ","
        + "Level:" + Level + ","
        + "}";
    }
}
}

