
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class AttrPair : Luban.BeanBase
{
    public AttrPair(ByteBuf _buf) 
    {
        Attr = (EAttrType)_buf.ReadInt();
        Val = _buf.ReadFloat();
    }

    public static AttrPair DeserializeAttrPair(ByteBuf _buf)
    {
        return new AttrPair(_buf);
    }

    public readonly EAttrType Attr;
    public readonly float Val;
   
    public const int __ID__ = 618509451;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Attr:" + Attr + ","
        + "Val:" + Val + ","
        + "}";
    }
}
}

