
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class BuffPacker : Luban.BeanBase
{
    public BuffPacker(ByteBuf _buf) 
    {
        BuffID = _buf.ReadInt();
        Duration = _buf.ReadFloat();
        Stack = _buf.ReadInt();
    }

    public static BuffPacker DeserializeBuffPacker(ByteBuf _buf)
    {
        return new BuffPacker(_buf);
    }

    public readonly int BuffID;
    public readonly float Duration;
    public readonly int Stack;
   
    public const int __ID__ = -1011705127;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BuffID:" + BuffID + ","
        + "Duration:" + Duration + ","
        + "Stack:" + Stack + ","
        + "}";
    }
}
}

