
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class BuffConfig : Luban.BeanBase
{
    public BuffConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        MaxStack = _buf.ReadInt();
        ValidTimeInterval = _buf.ReadFloat();
        ExpectedDuration = _buf.ReadFloat();
        AttachMethod = (EBuffAttachMethod)_buf.ReadInt();
        DetachMethod = (EBuffDetachMethod)_buf.ReadInt();
        HookMask = (EBuffHookMask)_buf.ReadInt();
        OnlyExecuteOnce = _buf.ReadBool();
    }

    public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
    {
        return new BuffConfig(_buf);
    }

    /// <summary>
    /// BuffID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 最大层数
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// 有效间隔秒数
    /// </summary>
    public readonly float ValidTimeInterval;
    /// <summary>
    /// 预期持续时间
    /// </summary>
    public readonly float ExpectedDuration;
    /// <summary>
    /// 叠层刷新策略
    /// </summary>
    public readonly EBuffAttachMethod AttachMethod;
    /// <summary>
    /// 消层刷新策略
    /// </summary>
    public readonly EBuffDetachMethod DetachMethod;
    /// <summary>
    /// Buff触发位掩码
    /// </summary>
    public readonly EBuffHookMask HookMask;
    /// <summary>
    /// 是否仅触发一次
    /// </summary>
    public readonly bool OnlyExecuteOnce;
   
    public const int __ID__ = -1370631787;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "MaxStack:" + MaxStack + ","
        + "ValidTimeInterval:" + ValidTimeInterval + ","
        + "ExpectedDuration:" + ExpectedDuration + ","
        + "AttachMethod:" + AttachMethod + ","
        + "DetachMethod:" + DetachMethod + ","
        + "HookMask:" + HookMask + ","
        + "OnlyExecuteOnce:" + OnlyExecuteOnce + ","
        + "}";
    }
}
}

