
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ChangeCurrencyItemSignal : ServerConfigableSignal
{
    public ChangeCurrencyItemSignal(ByteBuf _buf)  : base(_buf) 
    {
        IndexID = _buf.ReadInt();
        Count = _buf.ReadInt();
        IsAdd = _buf.ReadBool();
    }

    public static ChangeCurrencyItemSignal DeserializeChangeCurrencyItemSignal(ByteBuf _buf)
    {
        return new ChangeCurrencyItemSignal(_buf);
    }

    public readonly int IndexID;
    public readonly int Count;
    public readonly bool IsAdd;
   
    public const int __ID__ = 2009665148;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "IndexID:" + IndexID + ","
        + "Count:" + Count + ","
        + "IsAdd:" + IsAdd + ","
        + "}";
    }
}
}

