
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ChangeStackItemSignal : ServerConfigableSignal
{
    public ChangeStackItemSignal(ByteBuf _buf)  : base(_buf) 
    {
        ConfigID = _buf.ReadInt();
        Count = _buf.ReadInt();
        IsAdd = _buf.ReadBool();
    }

    public static ChangeStackItemSignal DeserializeChangeStackItemSignal(ByteBuf _buf)
    {
        return new ChangeStackItemSignal(_buf);
    }

    /// <summary>
    /// 从这里开始都是仅服务端信号
    /// </summary>
    public readonly int ConfigID;
    public readonly int Count;
    public readonly bool IsAdd;
   
    public const int __ID__ = 971517523;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ConfigID:" + ConfigID + ","
        + "Count:" + Count + ","
        + "IsAdd:" + IsAdd + ","
        + "}";
    }
}
}

