
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class CharacterBaseConfig : Luban.BeanBase
{
    public CharacterBaseConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); BasePoints = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BasePoints.Add(_e0);}}
    }

    public static CharacterBaseConfig DeserializeCharacterBaseConfig(ByteBuf _buf)
    {
        return new CharacterBaseConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 基础属性
    /// </summary>
    public readonly System.Collections.Generic.List<int> BasePoints;
   
    public const int __ID__ = -1411345060;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "BasePoints:" + Luban.StringUtil.CollectionToString(BasePoints) + ","
        + "}";
    }
}
}

