
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public abstract partial class ClientConfigableSignal : Luban.BeanBase
{
    public ClientConfigableSignal(ByteBuf _buf) 
    {
    }

    public static ClientConfigableSignal DeserializeClientConfigableSignal(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case TryOpenPanelSignal.__ID__: return new TryOpenPanelSignal(_buf);
            case TryOpenShopPanelSignal.__ID__: return new TryOpenShopPanelSignal(_buf);
            case TryBranchSubQuestSignal.__ID__: return new TryBranchSubQuestSignal(_buf);
            case TrySetTempProgressSignal.__ID__: return new TrySetTempProgressSignal(_buf);
            case TryEnterDialogueSignal.__ID__: return new TryEnterDialogueSignal(_buf);
            case TryPushTipSignal.__ID__: return new TryPushTipSignal(_buf);
            case TrySetBaseProgressSignal.__ID__: return new TrySetBaseProgressSignal(_buf);
            case TryRefreshSceneAndPlayer.__ID__: return new TryRefreshSceneAndPlayer(_buf);
            case TryTeleportScene.__ID__: return new TryTeleportScene(_buf);
            case TrySpawnEnemy.__ID__: return new TrySpawnEnemy(_buf);
            case TryPlayBGM.__ID__: return new TryPlayBGM(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

