
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ConfigableQuery : Luban.BeanBase
{
    public ConfigableQuery(ByteBuf _buf) 
    {
        QueryType = (EConfigableQueryType)_buf.ReadInt();
        Para1 = _buf.ReadInt();
        Para2 = _buf.ReadInt();
        Para3 = _buf.ReadInt();
        Para4 = _buf.ReadInt();
        Para5 = _buf.ReadInt();
        Para6 = _buf.ReadInt();
        Para7 = _buf.ReadInt();
        Para8 = _buf.ReadInt();
    }

    public static ConfigableQuery DeserializeConfigableQuery(ByteBuf _buf)
    {
        return new ConfigableQuery(_buf);
    }

    public readonly EConfigableQueryType QueryType;
    public readonly int Para1;
    public readonly int Para2;
    public readonly int Para3;
    public readonly int Para4;
    public readonly int Para5;
    public readonly int Para6;
    public readonly int Para7;
    public readonly int Para8;
   
    public const int __ID__ = 1347263084;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "QueryType:" + QueryType + ","
        + "para1:" + Para1 + ","
        + "para2:" + Para2 + ","
        + "para3:" + Para3 + ","
        + "para4:" + Para4 + ","
        + "para5:" + Para5 + ","
        + "para6:" + Para6 + ","
        + "para7:" + Para7 + ","
        + "para8:" + Para8 + ","
        + "}";
    }
}
}

