
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ConsumablesConfig : Luban.BeanBase
{
    public ConsumablesConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        ActionName = _buf.ReadString();
        AppliedBuff = _buf.ReadInt();
        EnchantID = _buf.ReadInt();
    }

    public static ConsumablesConfig DeserializeConsumablesConfig(ByteBuf _buf)
    {
        return new ConsumablesConfig(_buf);
    }

    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 使用Item的动作
    /// </summary>
    public readonly string ActionName;
    /// <summary>
    /// 会增加的Buff
    /// </summary>
    public readonly int AppliedBuff;
    /// <summary>
    /// 会给武器的附魔
    /// </summary>
    public readonly int EnchantID;
   
    public const int __ID__ = -106001998;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ActionName:" + ActionName + ","
        + "AppliedBuff:" + AppliedBuff + ","
        + "EnchantID:" + EnchantID + ","
        + "}";
    }
}
}

