
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class CurrencyItem : Luban.BeanBase
{
    public CurrencyItem(ByteBuf _buf) 
    {
        Index = _buf.ReadInt();
        Count = _buf.ReadInt();
    }

    public static CurrencyItem DeserializeCurrencyItem(ByteBuf _buf)
    {
        return new CurrencyItem(_buf);
    }

    public readonly int Index;
    public readonly int Count;
   
    public const int __ID__ = 1169277668;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "Count:" + Count + ","
        + "}";
    }
}
}

