
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class DialogueOption : Luban.BeanBase
{
    public DialogueOption(ByteBuf _buf) 
    {
        {int n0 = _buf.ReadSize(); Queries = new System.Collections.Generic.List<ConfigableQuery>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ConfigableQuery _e0;  _e0 = global::cfg.ConfigableQuery.DeserializeConfigableQuery(_buf); Queries.Add(_e0);}}
        Text = _buf.ReadString();
        NextJumpProgress = _buf.ReadInt();
    }

    public static DialogueOption DeserializeDialogueOption(ByteBuf _buf)
    {
        return new DialogueOption(_buf);
    }

    public readonly System.Collections.Generic.List<ConfigableQuery> Queries;
    public readonly string Text;
    public readonly int NextJumpProgress;
   
    public const int __ID__ = 113334413;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Queries) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Queries:" + Luban.StringUtil.CollectionToString(Queries) + ","
        + "Text:" + Text + ","
        + "NextJumpProgress:" + NextJumpProgress + ","
        + "}";
    }
}
}

