
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EAttrType
    {
        None = 0,
        /// <summary>
        /// 基础力量补正
        /// </summary>
        BaseStrengthModifier = 15,
        /// <summary>
        /// 基础技巧补正
        /// </summary>
        BaseDexterityModifier = 16,
        /// <summary>
        /// 基础精神补正
        /// </summary>
        BaseSpiritModifier = 17,
        /// <summary>
        /// 基础生命最大值
        /// </summary>
        BaseMaxHealth = 101,
        /// <summary>
        /// 基础怒气最大值
        /// </summary>
        BaseMaxRage = 111,
        /// <summary>
        /// 基础自动回怒效率
        /// </summary>
        BaseRageAutoRecovery = 113,
        /// <summary>
        /// 基础怒气消耗倍率
        /// </summary>
        BaseRageConsumeMult = 114,
        /// <summary>
        /// 基础物攻
        /// </summary>
        BasePhysicalATK = 200,
        /// <summary>
        /// 基础物防
        /// </summary>
        BasePhysicalDEF = 201,
        /// <summary>
        /// 基础魔攻
        /// </summary>
        BaseMagicalATK = 210,
        /// <summary>
        /// 基础魔防
        /// </summary>
        BaseMagicalDEF = 211,
        /// <summary>
        /// 基础真伤
        /// </summary>
        BaseRealATK = 220,
        /// <summary>
        /// 基础真抗
        /// </summary>
        BaseRealDEF = 221,
        /// <summary>
        /// 基础施毒
        /// </summary>
        BasePoisonATK = 301,
        /// <summary>
        /// 基础毒抗
        /// </summary>
        BasePoisonResistance = 302,
        /// <summary>
        /// 基础消毒效率
        /// </summary>
        BasePoisonDecay = 303,
        /// <summary>
        /// 基础施穿
        /// </summary>
        BasePierceATK = 311,
        /// <summary>
        /// 基础穿抗
        /// </summary>
        BasePierceResistance = 312,
        /// <summary>
        /// 基础消穿效率
        /// </summary>
        BasePierceDecay = 313,
        /// <summary>
        /// 基础施麻
        /// </summary>
        BaseLightningATK = 321,
        /// <summary>
        /// 基础麻抗
        /// </summary>
        BaseLightningResistance = 322,
        /// <summary>
        /// 基础消麻效率
        /// </summary>
        BaseLightningDecay = 323,
        /// <summary>
        /// 基础消韧
        /// </summary>
        BasePoiseATK = 401,
        /// <summary>
        /// 基础韧性上限
        /// </summary>
        BasePoiseMax = 402,
        /// <summary>
        /// 基础韧性恢复
        /// </summary>
        BasePoiseDecay = 403,
        /// <summary>
        /// 最终力量补正
        /// </summary>
        CalcStrengthModifier = 1015,
        /// <summary>
        /// 最终技巧补正
        /// </summary>
        CalcDexterityModifier = 1016,
        /// <summary>
        /// 最终精神补正
        /// </summary>
        CalcSpiritModifier = 1017,
        /// <summary>
        /// 最终生命最大值
        /// </summary>
        CalcMaxHealth = 1101,
        /// <summary>
        /// 最终怒气最大值
        /// </summary>
        CalcMaxRage = 1111,
        /// <summary>
        /// 最终自动回怒效率
        /// </summary>
        CalcRageAutoRecovery = 1113,
        /// <summary>
        /// 最终怒气消耗倍率
        /// </summary>
        CalcRageConsumeMult = 1114,
        /// <summary>
        /// 最终物攻
        /// </summary>
        CalcPhysicalATK = 1200,
        /// <summary>
        /// 最终物防
        /// </summary>
        CalcPhysicalDEF = 1201,
        /// <summary>
        /// 最终魔攻
        /// </summary>
        CalcMagicalATK = 1210,
        /// <summary>
        /// 最终魔防
        /// </summary>
        CalcMagicalDEF = 1211,
        /// <summary>
        /// 最终真伤
        /// </summary>
        CalcRealATK = 1220,
        /// <summary>
        /// 最终真抗
        /// </summary>
        CalcRealDEF = 1221,
        /// <summary>
        /// 最终施毒
        /// </summary>
        CalcPoisonATK = 1301,
        /// <summary>
        /// 最终毒抗
        /// </summary>
        CalcPoisonResistance = 1302,
        /// <summary>
        /// 最终消毒效率
        /// </summary>
        CalcPoisonDecay = 1303,
        /// <summary>
        /// 最终施穿
        /// </summary>
        CalcPierceATK = 1311,
        /// <summary>
        /// 最终穿抗
        /// </summary>
        CalcPierceResistance = 1312,
        /// <summary>
        /// 最终消穿效率
        /// </summary>
        CalcPierceDecay = 1313,
        /// <summary>
        /// 最终施麻
        /// </summary>
        CalcLightningATK = 1321,
        /// <summary>
        /// 最终麻抗
        /// </summary>
        CalcLightningResistance = 1322,
        /// <summary>
        /// 最终消麻效率
        /// </summary>
        CalcLightningDecay = 1323,
        /// <summary>
        /// 最终消韧
        /// </summary>
        CalcPoiseATK = 1401,
        /// <summary>
        /// 最终韧性上限
        /// </summary>
        CalcPoiseMax = 1402,
        /// <summary>
        /// 最终韧性恢复
        /// </summary>
        CalcPoiseDecay = 1403,
        /// <summary>
        /// 基础最大生命值加成
        /// </summary>
        BaseMaxHealthRate = 2101,
        /// <summary>
        /// 基础怒气最大值加成
        /// </summary>
        BaseMaxRageRate = 2111,
        /// <summary>
        /// 基础物攻加成
        /// </summary>
        BasePhysicalATKRate = 2200,
        /// <summary>
        /// 基础物防加成
        /// </summary>
        BasePhysicalDEFRate = 2201,
        /// <summary>
        /// 基础魔攻加成
        /// </summary>
        BaseMagicalATKRate = 2210,
        /// <summary>
        /// 基础魔防加成
        /// </summary>
        BaseMagicalDEFRate = 2211,
        /// <summary>
        /// 基础真伤加成
        /// </summary>
        BaseRealATKRate = 2220,
        /// <summary>
        /// 基础真抗加成
        /// </summary>
        BaseRealDEFRate = 2221,
        /// <summary>
        /// 基础施毒加成
        /// </summary>
        BasePoisonATKRate = 2301,
        /// <summary>
        /// 基础毒抗加成
        /// </summary>
        BasePoisonResistanceRate = 2302,
        /// <summary>
        /// 基础施穿加成
        /// </summary>
        BasePierceATKRate = 2311,
        /// <summary>
        /// 基础穿抗加成
        /// </summary>
        BasePierceResistanceRate = 2312,
        /// <summary>
        /// 基础施麻加成
        /// </summary>
        BaseLightningATKRate = 2321,
        /// <summary>
        /// 基础麻抗加成
        /// </summary>
        BaseLightningResistanceRate = 2322,
        /// <summary>
        /// 最终最大生命值加成
        /// </summary>
        CalcMaxHealthRate = 3101,
        /// <summary>
        /// 最终怒气最大值加成
        /// </summary>
        CalcMaxRageRate = 3111,
        /// <summary>
        /// 最终物攻加成
        /// </summary>
        CalcPhysicalATKRate = 3200,
        /// <summary>
        /// 最终物防加成
        /// </summary>
        CalcPhysicalDEFRate = 3201,
        /// <summary>
        /// 最终魔攻加成
        /// </summary>
        CalcMagicalATKRate = 3210,
        /// <summary>
        /// 最终魔防加成
        /// </summary>
        CalcMagicalDEFRate = 3211,
        /// <summary>
        /// 最终真伤加成
        /// </summary>
        CalcRealATKRate = 3220,
        /// <summary>
        /// 最终真抗加成
        /// </summary>
        CalcRealDEFRate = 3221,
        /// <summary>
        /// 最终施毒加成
        /// </summary>
        CalcPoisonATKRate = 3301,
        /// <summary>
        /// 最终毒抗加成
        /// </summary>
        CalcPoisonResistanceRate = 3302,
        /// <summary>
        /// 最终施穿加成
        /// </summary>
        CalcPierceATKRate = 3311,
        /// <summary>
        /// 最终穿抗加成
        /// </summary>
        CalcPierceResistanceRate = 3312,
        /// <summary>
        /// 最终施麻加成
        /// </summary>
        CalcLightningATKRate = 3321,
        /// <summary>
        /// 最终麻抗加成
        /// </summary>
        CalcLightningResistanceRate = 3322,
        /// <summary>
        /// 当前生命
        /// </summary>
        Health = 4100,
        /// <summary>
        /// 当前怒气
        /// </summary>
        Rage = 4110,
        /// <summary>
        /// 当前中毒累积
        /// </summary>
        CurrentPoisonAccumulate = 4300,
        /// <summary>
        /// 当前穿刺累积
        /// </summary>
        CurrentPierceAccumulate = 4310,
        /// <summary>
        /// 当前麻痹累积
        /// </summary>
        CurrentLightningAccumulate = 4320,
        /// <summary>
        /// 当前失衡值
        /// </summary>
        CurrentPoiseAccumulate = 4400,
        /// <summary>
        /// 最终加速度
        /// </summary>
        CalcAcceleration = 5000,
        /// <summary>
        /// 最终减速度
        /// </summary>
        CalcDeceleration = 5001,
        /// <summary>
        /// 最终摩擦力
        /// </summary>
        CalcFriction = 5002,
        /// <summary>
        /// 最终最高速度
        /// </summary>
        CalcTopSpeed = 5003,
        /// <summary>
        /// 最终转向速度
        /// </summary>
        CalcRotationSpeed = 5005,
        /// <summary>
        /// 最终重力
        /// </summary>
        CalcGravity = 5006,
        /// <summary>
        /// 最终下坠重力
        /// </summary>
        CalcFallGravity = 5007,
        /// <summary>
        /// 最终最高下落速度
        /// </summary>
        CalcGravityTopSpeed = 5008,
        /// <summary>
        /// 加速度倍率
        /// </summary>
        AccelerationMultiplier = 5009,
        /// <summary>
        /// 减速倍率
        /// </summary>
        DecelerationMultiplier = 5010,
        /// <summary>
        /// 摩擦倍率
        /// </summary>
        FrictionMultiplier = 5011,
        /// <summary>
        /// 最高速度倍率
        /// </summary>
        TopSpeedMultiplier = 5012,
        /// <summary>
        /// 转向速度倍率
        /// </summary>
        RotationSpeedMultiplier = 5014,
        /// <summary>
        /// 重力倍率
        /// </summary>
        GravityMultiplier = 5015,
        /// <summary>
        /// 下坠重力倍率
        /// </summary>
        FallGravityMultiplier = 5016,
        /// <summary>
        /// 最高下落速度倍率
        /// </summary>
        GravityTopSpeedMultiplier = 5017,
        /// <summary>
        /// 最终击退力
        /// </summary>
        CalcSuperArmorATK = 5018,
        /// <summary>
        /// 最终霸体值
        /// </summary>
        CalcSuperArmorDEF = 5019,
        /// <summary>
        /// 最终破防值
        /// </summary>
        CalcParryATK = 5020,
        /// <summary>
        /// 最终防反值
        /// </summary>
        CalcParryDEF = 5021,
        /// <summary>
        /// 最终无敌值
        /// </summary>
        CalcInvulnerable = 5022,
        /// <summary>
        /// 动画局部根运动x轴倍率
        /// </summary>
        AnimLocalDelXMult = 5023,
        /// <summary>
        /// 动画局部根运动y轴倍率
        /// </summary>
        AnimLocalDelYMult = 5024,
        /// <summary>
        /// 动画局部根运动z轴倍率
        /// </summary>
        AnimLocalDelZMult = 5025,
    }

} 

