
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EAttackAttrType
    {
        CalcPhysicalATK = 1200,
        CalcMagicalATK = 1210,
        CalcRealATK = 1220,
        CalcPoisonATK = 1301,
        CalcPierceATK = 1311,
        CalcLightningATK = 1321,
        CalcPoiseATK = 1401,
        CalcSuperArmorATK = 5018,
        CalcParryATK = 5020,
    }

} 

