
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EAudioGroup
    {
        /// <summary>
        /// 无效
        /// </summary>
        NONE = 0,
        /// <summary>
        /// UI音效
        /// </summary>
        UI = 1,
        /// <summary>
        /// 子弹
        /// </summary>
        BULLET = 2,
        /// <summary>
        /// 脚步
        /// </summary>
        FOOTSTEP = 3,
        /// <summary>
        /// 技能
        /// </summary>
        SKILL = 4,
        /// <summary>
        /// 声音
        /// </summary>
        VOICE = 5,
    }

} 

