
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EBuffDetachMethod
    {
        /// <summary>
        /// 不做任何处理
        /// </summary>
        None = 0,
        /// <summary>
        /// 刷新时间
        /// </summary>
        Restart = 1,
        /// <summary>
        /// 解除所有层数
        /// </summary>
        RemoveAll = 2,
    }

} 

