
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    [System.Flags]
    public enum EBuffHookMask
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 每帧
        /// </summary>
        Tick = 1,
        /// <summary>
        /// 攻击结算前
        /// </summary>
        BeforeAttackArbitrate = 2,
        /// <summary>
        /// 受击结算前
        /// </summary>
        BeforeHurtArbitrate = 4,
        /// <summary>
        /// 攻击结算后
        /// </summary>
        AfterAttackArbitrate = 8,
        /// <summary>
        /// 受击结算后
        /// </summary>
        AfterHurtArbitrate = 16,
        /// <summary>
        /// 动作开始时
        /// </summary>
        ActionStart = 32,
        /// <summary>
        /// 变化应用前
        /// </summary>
        OnDamageResult = 64,
    }

} 

