
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EBuffAttachMethod
    {
        /// <summary>
        /// 不做任何处理
        /// </summary>
        None = 0,
        /// <summary>
        /// 刷新时间
        /// </summary>
        Restart = 1,
        /// <summary>
        /// 增加时间
        /// </summary>
        AddTime = 2,
    }

} 

