
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EConfigableQueryType
    {
        None = 0,
        StackItemQuery = 1,
        InstanceItemQuery = 2,
        WeaponSetItemQuery = 3,
        EquipSetItemQuery = 4,
        StatPointSetQuery = 5,
        QuestQuery = 6,
        BoardConfigIDQuery = 7,
        KillMonsterQuery = 8,
        BeatContactQuery = 9,
        DeathCountQuery = 10,
        WayPointTriggerQuery = 11,
    }

} 

