
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EEntityGroup
    {
        None = 0,
        /// <summary>
        /// 玩家
        /// </summary>
        PLAYER = 1,
        /// <summary>
        /// 敌人
        /// </summary>
        ENEMY = 2,
        /// <summary>
        /// 非玩家友好角色
        /// </summary>
        NPC = 3,
    }

} 

