
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EInteractableTriggerType
    {
        /// <summary>
        /// 主动
        /// </summary>
        Interact = 0,
        /// <summary>
        /// 触发
        /// </summary>
        TriggerEnter = 1,
        /// <summary>
        /// 禁用
        /// </summary>
        Forbidden = 2,
    }

} 

