
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EItemType
    {
        None = 0,
        /// <summary>
        /// 普通
        /// </summary>
        Stack = 1,
        /// <summary>
        /// 消耗品
        /// </summary>
        Consumables = 2,
        /// <summary>
        /// 武器
        /// </summary>
        Weapon = 3,
        /// <summary>
        /// 头盔
        /// </summary>
        Helmet = 4,
        /// <summary>
        /// 盔甲
        /// </summary>
        Armor = 5,
        /// <summary>
        /// 基石
        /// </summary>
        Stone = 6,
    }

} 

