
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class EnemyDropConfig : Luban.BeanBase
{
    public EnemyDropConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); DropItem = new System.Collections.Generic.List<EnemyDropItem>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { EnemyDropItem _e0;  _e0 = global::cfg.EnemyDropItem.DeserializeEnemyDropItem(_buf); DropItem.Add(_e0);}}
    }

    public static EnemyDropConfig DeserializeEnemyDropConfig(ByteBuf _buf)
    {
        return new EnemyDropConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 敌人掉落物+概率分布
    /// </summary>
    public readonly System.Collections.Generic.List<EnemyDropItem> DropItem;
   
    public const int __ID__ = -1747318631;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in DropItem) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "DropItem:" + Luban.StringUtil.CollectionToString(DropItem) + ","
        + "}";
    }
}
}

