
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class EnemyDropItem : Luban.BeanBase
{
    public EnemyDropItem(ByteBuf _buf) 
    {
        Ratio = _buf.ReadFloat();
        {int n0 = _buf.ReadSize(); RewardItems = new System.Collections.Generic.List<RewardItem>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { RewardItem _e0;  _e0 = global::cfg.RewardItem.DeserializeRewardItem(_buf); RewardItems.Add(_e0);}}
    }

    public static EnemyDropItem DeserializeEnemyDropItem(ByteBuf _buf)
    {
        return new EnemyDropItem(_buf);
    }

    public readonly float Ratio;
    public readonly System.Collections.Generic.List<RewardItem> RewardItems;
   
    public const int __ID__ = 1468754474;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in RewardItems) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Ratio:" + Ratio + ","
        + "RewardItems:" + Luban.StringUtil.CollectionToString(RewardItems) + ","
        + "}";
    }
}
}

