
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class EnemyBaseConfig : Luban.BeanBase
{
    public EnemyBaseConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
    }

    public static EnemyBaseConfig DeserializeEnemyBaseConfig(ByteBuf _buf)
    {
        return new EnemyBaseConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
   
    public const int __ID__ = 811331323;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "}";
    }
}
}

