
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EParentQuestState
    {
        Locking = 0,
        Waiting = 1,
        Executing = 2,
        Finished = 3,
        Rewarded = 4,
    }

} 

