
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class EquipablesConfig : Luban.BeanBase
{
    public EquipablesConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); BaseAttr = new System.Collections.Generic.List<AttrPair>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { AttrPair _e0;  _e0 = global::cfg.AttrPair.DeserializeAttrPair(_buf); BaseAttr.Add(_e0);}}
        {int n0 = _buf.ReadSize(); AppliedBuffIDs = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AppliedBuffIDs.Add(_e0);}}
        SpDesc = _buf.ReadString();
    }

    public static EquipablesConfig DeserializeEquipablesConfig(ByteBuf _buf)
    {
        return new EquipablesConfig(_buf);
    }

    /// <summary>
    /// 装备ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 基础属性
    /// </summary>
    public readonly System.Collections.Generic.List<AttrPair> BaseAttr;
    /// <summary>
    /// 穿戴装备后给予的Buff
    /// </summary>
    public readonly System.Collections.Generic.List<int> AppliedBuffIDs;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string SpDesc;
   
    public const int __ID__ = -1786151701;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in BaseAttr) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "BaseAttr:" + Luban.StringUtil.CollectionToString(BaseAttr) + ","
        + "AppliedBuffIDs:" + Luban.StringUtil.CollectionToString(AppliedBuffIDs) + ","
        + "SpDesc:" + SpDesc + ","
        + "}";
    }
}
}

