
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EUIGroup
    {
        NONE = 0,
        /// <summary>
        /// 扣血等特效
        /// </summary>
        VFX = 1,
        /// <summary>
        /// 游戏内血条等
        /// </summary>
        HUD = 2,
        /// <summary>
        /// 导航栏
        /// </summary>
        NAV = 3,
        /// <summary>
        /// 主要设置栏
        /// </summary>
        MAIN = 4,
        /// <summary>
        /// 主要设置栏的上级
        /// </summary>
        FULL = 5,
        /// <summary>
        /// 新手引导层
        /// </summary>
        GUIDE = 6,
        /// <summary>
        /// 窗口提示
        /// </summary>
        POP = 7,
        /// <summary>
        /// 系统弹窗
        /// </summary>
        TIP = 8,
    }

} 

