
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EVFXGroup
    {
        None = 0,
        Buff = 1,
        /// <summary>
        /// 击中
        /// </summary>
        Hit = 2,
        /// <summary>
        /// 子弹
        /// </summary>
        Projectile = 3,
        /// <summary>
        /// 斩击
        /// </summary>
        Slash = 4,
    }

} 

