
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum EWeaponModifier
    {
        None = 0,
        /// <summary>
        /// 武器力量补正百分比
        /// </summary>
        StrengthModifier = 1,
        /// <summary>
        /// 武器技巧补正百分比
        /// </summary>
        DexterityModifier = 2,
        /// <summary>
        /// 武器精神补正百分比
        /// </summary>
        SpiritModifier = 3,
    }

} 

