
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class GrowthRule : Luban.BeanBase
{
    public GrowthRule(ByteBuf _buf) 
    {
        TargetType = (EAttrType)_buf.ReadInt();
        MinVal = _buf.ReadInt();
        MaxVal = _buf.ReadInt();
        Factor = _buf.ReadFloat();
        Constant = _buf.ReadFloat();
    }

    public static GrowthRule DeserializeGrowthRule(ByteBuf _buf)
    {
        return new GrowthRule(_buf);
    }

    public readonly EAttrType TargetType;
    public readonly int MinVal;
    public readonly int MaxVal;
    public readonly float Factor;
    public readonly float Constant;
   
    public const int __ID__ = 877825411;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TargetType:" + TargetType + ","
        + "MinVal:" + MinVal + ","
        + "MaxVal:" + MaxVal + ","
        + "Factor:" + Factor + ","
        + "Constant:" + Constant + ","
        + "}";
    }
}
}

