
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class InstanceItem : Item
{
    public InstanceItem(ByteBuf _buf)  : base(_buf) 
    {
        Level = _buf.ReadInt();
    }

    public static InstanceItem DeserializeInstanceItem(ByteBuf _buf)
    {
        return new InstanceItem(_buf);
    }

    public readonly int Level;
   
    public const int __ID__ = -573667992;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ConfigID:" + ConfigID + ","
        + "Level:" + Level + ","
        + "}";
    }
}
}

