
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ItemConfig : Luban.BeanBase
{
    public ItemConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        ItemType = (EItemType)_buf.ReadInt();
        TypeID = _buf.ReadInt();
        MaxStack = _buf.ReadInt();
    }

    public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
    {
        return new ItemConfig(_buf);
    }

    /// <summary>
    /// 物品ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 物品类型
    /// </summary>
    public readonly EItemType ItemType;
    /// <summary>
    /// 物品具体ID
    /// </summary>
    public readonly int TypeID;
    /// <summary>
    /// 最大堆叠数
    /// </summary>
    public readonly int MaxStack;
   
    public const int __ID__ = -764023723;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ItemType:" + ItemType + ","
        + "TypeID:" + TypeID + ","
        + "MaxStack:" + MaxStack + ","
        + "}";
    }
}
}

