
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public abstract partial class Item : Luban.BeanBase
{
    public Item(ByteBuf _buf) 
    {
        ConfigID = _buf.ReadInt();
    }

    public static Item DeserializeItem(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case StackItem.__ID__: return new StackItem(_buf);
            case InstanceItem.__ID__: return new InstanceItem(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly int ConfigID;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ConfigID:" + ConfigID + ","
        + "}";
    }
}
}

