
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class MainQuestConfig : Luban.BeanBase
{
    public MainQuestConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); SubQuests = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); SubQuests.Add(_e0);}}
        FamilyID = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); PreQuestCond = new System.Collections.Generic.List<ConfigableQuery>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ConfigableQuery _e0;  _e0 = global::cfg.ConfigableQuery.DeserializeConfigableQuery(_buf); PreQuestCond.Add(_e0);}}
        {int n0 = _buf.ReadSize(); OnSuccessSignalList = new System.Collections.Generic.List<ServerConfigableSignal>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ServerConfigableSignal _e0;  _e0 = global::cfg.ServerConfigableSignal.DeserializeServerConfigableSignal(_buf); OnSuccessSignalList.Add(_e0);}}
        {int n0 = _buf.ReadSize(); QuestItemRewards = new System.Collections.Generic.List<Item>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Item _e0;  _e0 = global::cfg.Item.DeserializeItem(_buf); QuestItemRewards.Add(_e0);}}
        {int n0 = _buf.ReadSize(); QuestCurrencyRewards = new System.Collections.Generic.List<CurrencyItem>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { CurrencyItem _e0;  _e0 = global::cfg.CurrencyItem.DeserializeCurrencyItem(_buf); QuestCurrencyRewards.Add(_e0);}}
        {int n0 = _buf.ReadSize(); AffectedInteractableIDs = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AffectedInteractableIDs.Add(_e0);}}
    }

    public static MainQuestConfig DeserializeMainQuestConfig(ByteBuf _buf)
    {
        return new MainQuestConfig(_buf);
    }

    /// <summary>
    /// 主任务ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 次任务序列
    /// </summary>
    public readonly System.Collections.Generic.List<int> SubQuests;
    /// <summary>
    /// 族ID
    /// </summary>
    public readonly int FamilyID;
    /// <summary>
    /// 前置解锁条件
    /// </summary>
    public readonly System.Collections.Generic.List<ConfigableQuery> PreQuestCond;
    /// <summary>
    /// 任务完成时信号
    /// </summary>
    public readonly System.Collections.Generic.List<ServerConfigableSignal> OnSuccessSignalList;
    /// <summary>
    /// 物品奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Item> QuestItemRewards;
    /// <summary>
    /// 货币奖励
    /// </summary>
    public readonly System.Collections.Generic.List<CurrencyItem> QuestCurrencyRewards;
    /// <summary>
    /// 受影响的交互体ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> AffectedInteractableIDs;
   
    public const int __ID__ = 438735659;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in PreQuestCond) { _e?.ResolveRef(tables); }
        foreach (var _e in OnSuccessSignalList) { _e?.ResolveRef(tables); }
        foreach (var _e in QuestItemRewards) { _e?.ResolveRef(tables); }
        foreach (var _e in QuestCurrencyRewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "SubQuests:" + Luban.StringUtil.CollectionToString(SubQuests) + ","
        + "FamilyID:" + FamilyID + ","
        + "PreQuestCond:" + Luban.StringUtil.CollectionToString(PreQuestCond) + ","
        + "OnSuccessSignalList:" + Luban.StringUtil.CollectionToString(OnSuccessSignalList) + ","
        + "QuestItemRewards:" + Luban.StringUtil.CollectionToString(QuestItemRewards) + ","
        + "QuestCurrencyRewards:" + Luban.StringUtil.CollectionToString(QuestCurrencyRewards) + ","
        + "AffectedInteractableIDs:" + Luban.StringUtil.CollectionToString(AffectedInteractableIDs) + ","
        + "}";
    }
}
}

