
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class QuestConfig : Luban.BeanBase
{
    public QuestConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        ParentID = _buf.ReadInt();
        QuestDesc = _buf.ReadString();
        {int n0 = _buf.ReadSize(); EnterSignal = new System.Collections.Generic.List<ServerConfigableSignal>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ServerConfigableSignal _e0;  _e0 = global::cfg.ServerConfigableSignal.DeserializeServerConfigableSignal(_buf); EnterSignal.Add(_e0);}}
        {int n0 = _buf.ReadSize(); CompleteQueryCond = new System.Collections.Generic.List<SubQuestsCond>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { SubQuestsCond _e0;  _e0 = global::cfg.SubQuestsCond.DeserializeSubQuestsCond(_buf); CompleteQueryCond.Add(_e0);}}
        CanAutoSuccess = _buf.ReadBool();
        {int n0 = _buf.ReadSize(); TransitionsCond = new System.Collections.Generic.List<SubQuestTransistion>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { SubQuestTransistion _e0;  _e0 = global::cfg.SubQuestTransistion.DeserializeSubQuestTransistion(_buf); TransitionsCond.Add(_e0);}}
    }

    public static QuestConfig DeserializeQuestConfig(ByteBuf _buf)
    {
        return new QuestConfig(_buf);
    }

    /// <summary>
    /// 任务ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 父任务
    /// </summary>
    public readonly int ParentID;
    /// <summary>
    /// 任务描述
    /// </summary>
    public readonly string QuestDesc;
    /// <summary>
    /// 任务开始执行时执行信号
    /// </summary>
    public readonly System.Collections.Generic.List<ServerConfigableSignal> EnterSignal;
    /// <summary>
    /// 完成条件
    /// </summary>
    public readonly System.Collections.Generic.List<SubQuestsCond> CompleteQueryCond;
    /// <summary>
    /// 是否在满足条件后自动开始过渡
    /// </summary>
    public readonly bool CanAutoSuccess;
    /// <summary>
    /// 过渡Branch条件
    /// </summary>
    public readonly System.Collections.Generic.List<SubQuestTransistion> TransitionsCond;
   
    public const int __ID__ = 1544257188;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in EnterSignal) { _e?.ResolveRef(tables); }
        foreach (var _e in CompleteQueryCond) { _e?.ResolveRef(tables); }
        foreach (var _e in TransitionsCond) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ParentID:" + ParentID + ","
        + "QuestDesc:" + QuestDesc + ","
        + "EnterSignal:" + Luban.StringUtil.CollectionToString(EnterSignal) + ","
        + "CompleteQueryCond:" + Luban.StringUtil.CollectionToString(CompleteQueryCond) + ","
        + "CanAutoSuccess:" + CanAutoSuccess + ","
        + "TransitionsCond:" + Luban.StringUtil.CollectionToString(TransitionsCond) + ","
        + "}";
    }
}
}

