
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class RewardItem : Luban.BeanBase
{
    public RewardItem(ByteBuf _buf) 
    {
        ConfigID = _buf.ReadInt();
        Count = _buf.ReadInt();
        IsCurrency = _buf.ReadBool();
    }

    public static RewardItem DeserializeRewardItem(ByteBuf _buf)
    {
        return new RewardItem(_buf);
    }

    public readonly int ConfigID;
    public readonly int Count;
    public readonly bool IsCurrency;
   
    public const int __ID__ = -610604286;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ConfigID:" + ConfigID + ","
        + "Count:" + Count + ","
        + "IsCurrency:" + IsCurrency + ","
        + "}";
    }
}
}

