
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SceneEnemy : Luban.BeanBase
{
    public SceneEnemy(ByteBuf _buf) 
    {
        UID = _buf.ReadLong();
        ConfigID = _buf.ReadInt();
        WeaponConfigID = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); PatrolWayPoints = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); PatrolWayPoints.Add(_e0);}}
    }

    public static SceneEnemy DeserializeSceneEnemy(ByteBuf _buf)
    {
        return new SceneEnemy(_buf);
    }

    public readonly long UID;
    public readonly int ConfigID;
    public readonly int WeaponConfigID;
    public readonly System.Collections.Generic.List<int> PatrolWayPoints;
   
    public const int __ID__ = -245097860;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "UID:" + UID + ","
        + "ConfigID:" + ConfigID + ","
        + "WeaponConfigID:" + WeaponConfigID + ","
        + "PatrolWayPoints:" + Luban.StringUtil.CollectionToString(PatrolWayPoints) + ","
        + "}";
    }
}
}

