
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SceneEnemyConfig : Luban.BeanBase
{
    public SceneEnemyConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); SceneEnemies = new System.Collections.Generic.List<SceneEnemy>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { SceneEnemy _e0;  _e0 = global::cfg.SceneEnemy.DeserializeSceneEnemy(_buf); SceneEnemies.Add(_e0);}}
    }

    public static SceneEnemyConfig DeserializeSceneEnemyConfig(ByteBuf _buf)
    {
        return new SceneEnemyConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 场景中的敌人配置
    /// </summary>
    public readonly System.Collections.Generic.List<SceneEnemy> SceneEnemies;
   
    public const int __ID__ = -795755298;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in SceneEnemies) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "SceneEnemies:" + Luban.StringUtil.CollectionToString(SceneEnemies) + ","
        + "}";
    }
}
}

