
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public abstract partial class ServerConfigableSignal : Luban.BeanBase
{
    public ServerConfigableSignal(ByteBuf _buf) 
    {
    }

    public static ServerConfigableSignal DeserializeServerConfigableSignal(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case ChangeStackItemSignal.__ID__: return new ChangeStackItemSignal(_buf);
            case AddInstanceItemSignal.__ID__: return new AddInstanceItemSignal(_buf);
            case ChangeCurrencyItemSignal.__ID__: return new ChangeCurrencyItemSignal(_buf);
            case TryUnlockParentQuestSignal.__ID__: return new TryUnlockParentQuestSignal(_buf);
            case TrySetInteractableProgSignal.__ID__: return new TrySetInteractableProgSignal(_buf);
            case TrySetActiveWayPointSignal.__ID__: return new TrySetActiveWayPointSignal(_buf);
            case TryRewardSignal.__ID__: return new TryRewardSignal(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

