
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ShopItem : Luban.BeanBase
{
    public ShopItem(ByteBuf _buf) 
    {
        ItemConfigID = _buf.ReadInt();
        CurrencyID = _buf.ReadInt();
        CurrencyCount = _buf.ReadInt();
    }

    public static ShopItem DeserializeShopItem(ByteBuf _buf)
    {
        return new ShopItem(_buf);
    }

    public readonly int ItemConfigID;
    public readonly int CurrencyID;
    public readonly int CurrencyCount;
   
    public const int __ID__ = -280968375;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemConfigID:" + ItemConfigID + ","
        + "CurrencyID:" + CurrencyID + ","
        + "CurrencyCount:" + CurrencyCount + ","
        + "}";
    }
}
}

