
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ShopConfig : Luban.BeanBase
{
    public ShopConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); BuyItems = new System.Collections.Generic.List<ShopItem>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ShopItem _e0;  _e0 = global::cfg.ShopItem.DeserializeShopItem(_buf); BuyItems.Add(_e0);}}
        {int n0 = _buf.ReadSize(); SellItems = new System.Collections.Generic.List<ShopItem>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ShopItem _e0;  _e0 = global::cfg.ShopItem.DeserializeShopItem(_buf); SellItems.Add(_e0);}}
    }

    public static ShopConfig DeserializeShopConfig(ByteBuf _buf)
    {
        return new ShopConfig(_buf);
    }

    /// <summary>
    /// 商店ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 售出商品
    /// </summary>
    public readonly System.Collections.Generic.List<ShopItem> BuyItems;
    /// <summary>
    /// 回收商品
    /// </summary>
    public readonly System.Collections.Generic.List<ShopItem> SellItems;
   
    public const int __ID__ = 396203512;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in BuyItems) { _e?.ResolveRef(tables); }
        foreach (var _e in SellItems) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "BuyItems:" + Luban.StringUtil.CollectionToString(BuyItems) + ","
        + "SellItems:" + Luban.StringUtil.CollectionToString(SellItems) + ","
        + "}";
    }
}
}

