
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class StackItem : Item
{
    public StackItem(ByteBuf _buf)  : base(_buf) 
    {
        Count = _buf.ReadInt();
    }

    public static StackItem DeserializeStackItem(ByteBuf _buf)
    {
        return new StackItem(_buf);
    }

    public readonly int Count;
   
    public const int __ID__ = -563393125;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ConfigID:" + ConfigID + ","
        + "Count:" + Count + ","
        + "}";
    }
}
}

