
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class StatsPointConfig : Luban.BeanBase
{
    public StatsPointConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); GrowthList = new System.Collections.Generic.List<GrowthRule>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { GrowthRule _e0;  _e0 = global::cfg.GrowthRule.DeserializeGrowthRule(_buf); GrowthList.Add(_e0);}}
        {int n0 = _buf.ReadSize(); AffectedAttrs = new System.Collections.Generic.List<EAttrType>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { EAttrType _e0;  _e0 = (EAttrType)_buf.ReadInt(); AffectedAttrs.Add(_e0);}}
    }

    public static StatsPointConfig DeserializeStatsPointConfig(ByteBuf _buf)
    {
        return new StatsPointConfig(_buf);
    }

    /// <summary>
    /// 属性id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 受影响的属性/等级区间/区间内每级增量/常数增量
    /// </summary>
    public readonly System.Collections.Generic.List<GrowthRule> GrowthList;
    /// <summary>
    /// 受影响的属性
    /// </summary>
    public readonly System.Collections.Generic.List<EAttrType> AffectedAttrs;
   
    public const int __ID__ = 1309062899;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in GrowthList) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "GrowthList:" + Luban.StringUtil.CollectionToString(GrowthList) + ","
        + "AffectedAttrs:" + Luban.StringUtil.CollectionToString(AffectedAttrs) + ","
        + "}";
    }
}
}

