
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SubQuestTransistion : Luban.BeanBase
{
    public SubQuestTransistion(ByteBuf _buf) 
    {
        BranchID = _buf.ReadInt();
        TargetSubQuestID = _buf.ReadInt();
    }

    public static SubQuestTransistion DeserializeSubQuestTransistion(ByteBuf _buf)
    {
        return new SubQuestTransistion(_buf);
    }

    public readonly int BranchID;
    public readonly int TargetSubQuestID;
   
    public const int __ID__ = -2050103324;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BranchID:" + BranchID + ","
        + "TargetSubQuestID:" + TargetSubQuestID + ","
        + "}";
    }
}
}

