
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SubQuestsCond : Luban.BeanBase
{
    public SubQuestsCond(ByteBuf _buf) 
    {
        Query = global::cfg.ConfigableQuery.DeserializeConfigableQuery(_buf);
        CanNotify = _buf.ReadBool();
        RefCount = _buf.ReadInt();
        Desc = _buf.ReadString();
        WayPointID = _buf.ReadInt();
        SceneID = _buf.ReadInt();
    }

    public static SubQuestsCond DeserializeSubQuestsCond(ByteBuf _buf)
    {
        return new SubQuestsCond(_buf);
    }

    public readonly ConfigableQuery Query;
    public readonly bool CanNotify;
    public readonly int RefCount;
    public readonly string Desc;
    public readonly int WayPointID;
    public readonly int SceneID;
   
    public const int __ID__ = 1919275219;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Query?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Query:" + Query + ","
        + "CanNotify:" + CanNotify + ","
        + "RefCount:" + RefCount + ","
        + "Desc:" + Desc + ","
        + "WayPointID:" + WayPointID + ","
        + "SceneID:" + SceneID + ","
        + "}";
    }
}
}

