
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public TbBuffConfig TbBuffConfig {get; }
    public TbConsumablesConfig TbConsumablesConfig {get; }
    public TbEquipablesConfig TbEquipablesConfig {get; }
    public TbItemConfig TbItemConfig {get; }
    public TbStatsPointConfig TbStatsPointConfig {get; }
    public TbWeaponConfig TbWeaponConfig {get; }
    public TbCharacterBaseConfig TbCharacterBaseConfig {get; }
    public TbWeaponEnchantmentConfig TbWeaponEnchantmentConfig {get; }
    public TbEnemyBaseConfig TbEnemyBaseConfig {get; }
    public TbSceneEnemyConfig TbSceneEnemyConfig {get; }
    public TbMainQuestConfig TbMainQuestConfig {get; }
    public TbQuestConfig TbQuestConfig {get; }
    public TbShopConfig TbShopConfig {get; }
    public TbEnemyDropConfig TbEnemyDropConfig {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbBuffConfig = new TbBuffConfig(loader("tbbuffconfig"));
        TbConsumablesConfig = new TbConsumablesConfig(loader("tbconsumablesconfig"));
        TbEquipablesConfig = new TbEquipablesConfig(loader("tbequipablesconfig"));
        TbItemConfig = new TbItemConfig(loader("tbitemconfig"));
        TbStatsPointConfig = new TbStatsPointConfig(loader("tbstatspointconfig"));
        TbWeaponConfig = new TbWeaponConfig(loader("tbweaponconfig"));
        TbCharacterBaseConfig = new TbCharacterBaseConfig(loader("tbcharacterbaseconfig"));
        TbWeaponEnchantmentConfig = new TbWeaponEnchantmentConfig(loader("tbweaponenchantmentconfig"));
        TbEnemyBaseConfig = new TbEnemyBaseConfig(loader("tbenemybaseconfig"));
        TbSceneEnemyConfig = new TbSceneEnemyConfig(loader("tbsceneenemyconfig"));
        TbMainQuestConfig = new TbMainQuestConfig(loader("tbmainquestconfig"));
        TbQuestConfig = new TbQuestConfig(loader("tbquestconfig"));
        TbShopConfig = new TbShopConfig(loader("tbshopconfig"));
        TbEnemyDropConfig = new TbEnemyDropConfig(loader("tbenemydropconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbBuffConfig.ResolveRef(this);
        TbConsumablesConfig.ResolveRef(this);
        TbEquipablesConfig.ResolveRef(this);
        TbItemConfig.ResolveRef(this);
        TbStatsPointConfig.ResolveRef(this);
        TbWeaponConfig.ResolveRef(this);
        TbCharacterBaseConfig.ResolveRef(this);
        TbWeaponEnchantmentConfig.ResolveRef(this);
        TbEnemyBaseConfig.ResolveRef(this);
        TbSceneEnemyConfig.ResolveRef(this);
        TbMainQuestConfig.ResolveRef(this);
        TbQuestConfig.ResolveRef(this);
        TbShopConfig.ResolveRef(this);
        TbEnemyDropConfig.ResolveRef(this);
    }
}

}
