
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbBuffConfig
{
    private readonly System.Collections.Generic.Dictionary<int, BuffConfig> _dataMap;
    private readonly System.Collections.Generic.List<BuffConfig> _dataList;
    
    public TbBuffConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, BuffConfig>(n);
        _dataList = new System.Collections.Generic.List<BuffConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            BuffConfig _v;
            _v = global::cfg.BuffConfig.DeserializeBuffConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, BuffConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<BuffConfig> DataList => _dataList;

    public BuffConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BuffConfig Get(int key) => _dataMap[key];
    public BuffConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

