
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbCharacterBaseConfig
{
    private readonly System.Collections.Generic.Dictionary<int, CharacterBaseConfig> _dataMap;
    private readonly System.Collections.Generic.List<CharacterBaseConfig> _dataList;
    
    public TbCharacterBaseConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, CharacterBaseConfig>(n);
        _dataList = new System.Collections.Generic.List<CharacterBaseConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            CharacterBaseConfig _v;
            _v = global::cfg.CharacterBaseConfig.DeserializeCharacterBaseConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, CharacterBaseConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<CharacterBaseConfig> DataList => _dataList;

    public CharacterBaseConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CharacterBaseConfig Get(int key) => _dataMap[key];
    public CharacterBaseConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

