
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbConsumablesConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ConsumablesConfig> _dataMap;
    private readonly System.Collections.Generic.List<ConsumablesConfig> _dataList;
    
    public TbConsumablesConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ConsumablesConfig>(n);
        _dataList = new System.Collections.Generic.List<ConsumablesConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ConsumablesConfig _v;
            _v = global::cfg.ConsumablesConfig.DeserializeConsumablesConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, ConsumablesConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ConsumablesConfig> DataList => _dataList;

    public ConsumablesConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ConsumablesConfig Get(int key) => _dataMap[key];
    public ConsumablesConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

