
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbEnemyBaseConfig
{
    private readonly System.Collections.Generic.Dictionary<int, EnemyBaseConfig> _dataMap;
    private readonly System.Collections.Generic.List<EnemyBaseConfig> _dataList;
    
    public TbEnemyBaseConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, EnemyBaseConfig>(n);
        _dataList = new System.Collections.Generic.List<EnemyBaseConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            EnemyBaseConfig _v;
            _v = global::cfg.EnemyBaseConfig.DeserializeEnemyBaseConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, EnemyBaseConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<EnemyBaseConfig> DataList => _dataList;

    public EnemyBaseConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public EnemyBaseConfig Get(int key) => _dataMap[key];
    public EnemyBaseConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

