
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbEnemyDropConfig
{
    private readonly System.Collections.Generic.Dictionary<int, EnemyDropConfig> _dataMap;
    private readonly System.Collections.Generic.List<EnemyDropConfig> _dataList;
    
    public TbEnemyDropConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, EnemyDropConfig>(n);
        _dataList = new System.Collections.Generic.List<EnemyDropConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            EnemyDropConfig _v;
            _v = global::cfg.EnemyDropConfig.DeserializeEnemyDropConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, EnemyDropConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<EnemyDropConfig> DataList => _dataList;

    public EnemyDropConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public EnemyDropConfig Get(int key) => _dataMap[key];
    public EnemyDropConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

