
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbEquipablesConfig
{
    private readonly System.Collections.Generic.Dictionary<int, EquipablesConfig> _dataMap;
    private readonly System.Collections.Generic.List<EquipablesConfig> _dataList;
    
    public TbEquipablesConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, EquipablesConfig>(n);
        _dataList = new System.Collections.Generic.List<EquipablesConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            EquipablesConfig _v;
            _v = global::cfg.EquipablesConfig.DeserializeEquipablesConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, EquipablesConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<EquipablesConfig> DataList => _dataList;

    public EquipablesConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public EquipablesConfig Get(int key) => _dataMap[key];
    public EquipablesConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

