
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbMainQuestConfig
{
    private readonly System.Collections.Generic.Dictionary<int, MainQuestConfig> _dataMap;
    private readonly System.Collections.Generic.List<MainQuestConfig> _dataList;
    
    public TbMainQuestConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, MainQuestConfig>(n);
        _dataList = new System.Collections.Generic.List<MainQuestConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            MainQuestConfig _v;
            _v = global::cfg.MainQuestConfig.DeserializeMainQuestConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, MainQuestConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<MainQuestConfig> DataList => _dataList;

    public MainQuestConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public MainQuestConfig Get(int key) => _dataMap[key];
    public MainQuestConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

