
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbQuestConfig
{
    private readonly System.Collections.Generic.Dictionary<int, QuestConfig> _dataMap;
    private readonly System.Collections.Generic.List<QuestConfig> _dataList;
    
    public TbQuestConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, QuestConfig>(n);
        _dataList = new System.Collections.Generic.List<QuestConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            QuestConfig _v;
            _v = global::cfg.QuestConfig.DeserializeQuestConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, QuestConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<QuestConfig> DataList => _dataList;

    public QuestConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public QuestConfig Get(int key) => _dataMap[key];
    public QuestConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

