
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbSceneEnemyConfig
{
    private readonly System.Collections.Generic.Dictionary<int, SceneEnemyConfig> _dataMap;
    private readonly System.Collections.Generic.List<SceneEnemyConfig> _dataList;
    
    public TbSceneEnemyConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, SceneEnemyConfig>(n);
        _dataList = new System.Collections.Generic.List<SceneEnemyConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            SceneEnemyConfig _v;
            _v = global::cfg.SceneEnemyConfig.DeserializeSceneEnemyConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, SceneEnemyConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<SceneEnemyConfig> DataList => _dataList;

    public SceneEnemyConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SceneEnemyConfig Get(int key) => _dataMap[key];
    public SceneEnemyConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

