
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbShopConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ShopConfig> _dataMap;
    private readonly System.Collections.Generic.List<ShopConfig> _dataList;
    
    public TbShopConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ShopConfig>(n);
        _dataList = new System.Collections.Generic.List<ShopConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ShopConfig _v;
            _v = global::cfg.ShopConfig.DeserializeShopConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, ShopConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ShopConfig> DataList => _dataList;

    public ShopConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ShopConfig Get(int key) => _dataMap[key];
    public ShopConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

