
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbStatsPointConfig
{
    private readonly System.Collections.Generic.Dictionary<int, StatsPointConfig> _dataMap;
    private readonly System.Collections.Generic.List<StatsPointConfig> _dataList;
    
    public TbStatsPointConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, StatsPointConfig>(n);
        _dataList = new System.Collections.Generic.List<StatsPointConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            StatsPointConfig _v;
            _v = global::cfg.StatsPointConfig.DeserializeStatsPointConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, StatsPointConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<StatsPointConfig> DataList => _dataList;

    public StatsPointConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public StatsPointConfig Get(int key) => _dataMap[key];
    public StatsPointConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

