
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbWeaponEnchantmentConfig
{
    private readonly System.Collections.Generic.Dictionary<int, WeaponEnchantmentConfig> _dataMap;
    private readonly System.Collections.Generic.List<WeaponEnchantmentConfig> _dataList;
    
    public TbWeaponEnchantmentConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, WeaponEnchantmentConfig>(n);
        _dataList = new System.Collections.Generic.List<WeaponEnchantmentConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            WeaponEnchantmentConfig _v;
            _v = global::cfg.WeaponEnchantmentConfig.DeserializeWeaponEnchantmentConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, WeaponEnchantmentConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<WeaponEnchantmentConfig> DataList => _dataList;

    public WeaponEnchantmentConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public WeaponEnchantmentConfig Get(int key) => _dataMap[key];
    public WeaponEnchantmentConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

