
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TryBranchSubQuestSignal : ClientConfigableSignal
{
    public TryBranchSubQuestSignal(ByteBuf _buf)  : base(_buf) 
    {
        TargetSubQuestID = _buf.ReadInt();
        BranchID = _buf.ReadInt();
    }

    public static TryBranchSubQuestSignal DeserializeTryBranchSubQuestSignal(ByteBuf _buf)
    {
        return new TryBranchSubQuestSignal(_buf);
    }

    public readonly int TargetSubQuestID;
    public readonly int BranchID;
   
    public const int __ID__ = 139809863;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "TargetSubQuestID:" + TargetSubQuestID + ","
        + "BranchID:" + BranchID + ","
        + "}";
    }
}
}

