
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TryEnterDialogueSignal : ClientConfigableSignal
{
    public TryEnterDialogueSignal(ByteBuf _buf)  : base(_buf) 
    {
        BaseDialogueID = _buf.ReadInt();
        OverrideDialogueID = _buf.ReadInt();
        UseOverride = _buf.ReadBool();
    }

    public static TryEnterDialogueSignal DeserializeTryEnterDialogueSignal(ByteBuf _buf)
    {
        return new TryEnterDialogueSignal(_buf);
    }

    public readonly int BaseDialogueID;
    public readonly int OverrideDialogueID;
    public readonly bool UseOverride;
   
    public const int __ID__ = -1115744771;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "BaseDialogueID:" + BaseDialogueID + ","
        + "OverrideDialogueID:" + OverrideDialogueID + ","
        + "UseOverride:" + UseOverride + ","
        + "}";
    }
}
}

