
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TryOpenPanelSignal : ClientConfigableSignal
{
    public TryOpenPanelSignal(ByteBuf _buf)  : base(_buf) 
    {
        UIAssetName = _buf.ReadString();
        Group = (EUIGroup)_buf.ReadInt();
        WaitClose = _buf.ReadBool();
    }

    public static TryOpenPanelSignal DeserializeTryOpenPanelSignal(ByteBuf _buf)
    {
        return new TryOpenPanelSignal(_buf);
    }

    /// <summary>
    /// 从这里开始都是仅客户端信号
    /// </summary>
    public readonly string UIAssetName;
    public readonly EUIGroup Group;
    public readonly bool WaitClose;
   
    public const int __ID__ = -1434515961;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "UIAssetName:" + UIAssetName + ","
        + "Group:" + Group + ","
        + "WaitClose:" + WaitClose + ","
        + "}";
    }
}
}

