
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TryOpenShopPanelSignal : ClientConfigableSignal
{
    public TryOpenShopPanelSignal(ByteBuf _buf)  : base(_buf) 
    {
        ID = _buf.ReadInt();
    }

    public static TryOpenShopPanelSignal DeserializeTryOpenShopPanelSignal(ByteBuf _buf)
    {
        return new TryOpenShopPanelSignal(_buf);
    }

    public readonly int ID;
   
    public const int __ID__ = -861870159;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "}";
    }
}
}

