
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TryPushTipSignal : ClientConfigableSignal
{
    public TryPushTipSignal(ByteBuf _buf)  : base(_buf) 
    {
        TipText = _buf.ReadString();
    }

    public static TryPushTipSignal DeserializeTryPushTipSignal(ByteBuf _buf)
    {
        return new TryPushTipSignal(_buf);
    }

    public readonly string TipText;
   
    public const int __ID__ = -247504050;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "TipText:" + TipText + ","
        + "}";
    }
}
}

