
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TryPlayBGM : ClientConfigableSignal
{
    public TryPlayBGM(ByteBuf _buf)  : base(_buf) 
    {
        BGMName = _buf.ReadString();
    }

    public static TryPlayBGM DeserializeTryPlayBGM(ByteBuf _buf)
    {
        return new TryPlayBGM(_buf);
    }

    public readonly string BGMName;
   
    public const int __ID__ = -1915907367;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "BGMName:" + BGMName + ","
        + "}";
    }
}
}

