
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TryRewardSignal : ServerConfigableSignal
{
    public TryRewardSignal(ByteBuf _buf)  : base(_buf) 
    {
        ParentQuestID = _buf.ReadInt();
    }

    public static TryRewardSignal DeserializeTryRewardSignal(ByteBuf _buf)
    {
        return new TryRewardSignal(_buf);
    }

    public readonly int ParentQuestID;
   
    public const int __ID__ = 1035163634;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ParentQuestID:" + ParentQuestID + ","
        + "}";
    }
}
}

