
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TrySpawnEnemy : ClientConfigableSignal
{
    public TrySpawnEnemy(ByteBuf _buf)  : base(_buf) 
    {
        EnemyUID = _buf.ReadLong();
    }

    public static TrySpawnEnemy DeserializeTrySpawnEnemy(ByteBuf _buf)
    {
        return new TrySpawnEnemy(_buf);
    }

    public readonly long EnemyUID;
   
    public const int __ID__ = -721485624;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "EnemyUID:" + EnemyUID + ","
        + "}";
    }
}
}

