
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TrySetInteractableProgSignal : ServerConfigableSignal
{
    public TrySetInteractableProgSignal(ByteBuf _buf)  : base(_buf) 
    {
        InteractableID = _buf.ReadInt();
        Progress = _buf.ReadInt();
        Priority = _buf.ReadInt();
    }

    public static TrySetInteractableProgSignal DeserializeTrySetInteractableProgSignal(ByteBuf _buf)
    {
        return new TrySetInteractableProgSignal(_buf);
    }

    public readonly int InteractableID;
    public readonly int Progress;
    /// <summary>
    /// 取-1时为永久覆盖
    /// </summary>
    public readonly int Priority;
   
    public const int __ID__ = 1633925369;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "InteractableID:" + InteractableID + ","
        + "Progress:" + Progress + ","
        + "Priority:" + Priority + ","
        + "}";
    }
}
}

