
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TrySetTempProgressSignal : ClientConfigableSignal
{
    public TrySetTempProgressSignal(ByteBuf _buf)  : base(_buf) 
    {
        InteractableID = _buf.ReadInt();
        Progress = _buf.ReadInt();
    }

    public static TrySetTempProgressSignal DeserializeTrySetTempProgressSignal(ByteBuf _buf)
    {
        return new TrySetTempProgressSignal(_buf);
    }

    public readonly int InteractableID;
    public readonly int Progress;
   
    public const int __ID__ = -100311728;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "InteractableID:" + InteractableID + ","
        + "Progress:" + Progress + ","
        + "}";
    }
}
}

