
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TrySetActiveWayPointSignal : ServerConfigableSignal
{
    public TrySetActiveWayPointSignal(ByteBuf _buf)  : base(_buf) 
    {
        WayPointID = _buf.ReadInt();
        IsActive = _buf.ReadBool();
    }

    public static TrySetActiveWayPointSignal DeserializeTrySetActiveWayPointSignal(ByteBuf _buf)
    {
        return new TrySetActiveWayPointSignal(_buf);
    }

    public readonly int WayPointID;
    public readonly bool IsActive;
   
    public const int __ID__ = -1873827338;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "WayPointID:" + WayPointID + ","
        + "IsActive:" + IsActive + ","
        + "}";
    }
}
}

