
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TryTeleportScene : ClientConfigableSignal
{
    public TryTeleportScene(ByteBuf _buf)  : base(_buf) 
    {
        SceneID = _buf.ReadInt();
        RevivePointID = _buf.ReadInt();
    }

    public static TryTeleportScene DeserializeTryTeleportScene(ByteBuf _buf)
    {
        return new TryTeleportScene(_buf);
    }

    public readonly int SceneID;
    public readonly int RevivePointID;
   
    public const int __ID__ = -2000974266;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "SceneID:" + SceneID + ","
        + "RevivePointID:" + RevivePointID + ","
        + "}";
    }
}
}

