
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class TryUnlockParentQuestSignal : ServerConfigableSignal
{
    public TryUnlockParentQuestSignal(ByteBuf _buf)  : base(_buf) 
    {
        TargetParentQuestID = _buf.ReadInt();
    }

    public static TryUnlockParentQuestSignal DeserializeTryUnlockParentQuestSignal(ByteBuf _buf)
    {
        return new TryUnlockParentQuestSignal(_buf);
    }

    public readonly int TargetParentQuestID;
   
    public const int __ID__ = -1268091871;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "TargetParentQuestID:" + TargetParentQuestID + ","
        + "}";
    }
}
}

