
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class WeaponConfig : Luban.BeanBase
{
    public WeaponConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); UpdateExp = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); UpdateExp.Add(_e0);}}
        MaxLevel = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); AbilityDemand = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AbilityDemand.Add(_e0);}}
        {int n0 = _buf.ReadSize(); BaseAttr = new System.Collections.Generic.List<AttrPair>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { AttrPair _e0;  _e0 = global::cfg.AttrPair.DeserializeAttrPair(_buf); BaseAttr.Add(_e0);}}
        {int n0 = _buf.ReadSize(); BaseModifier = new System.Collections.Generic.List<WeaponAttrPair>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { WeaponAttrPair _e0;  _e0 = global::cfg.WeaponAttrPair.DeserializeWeaponAttrPair(_buf); BaseModifier.Add(_e0);}}
        {int n0 = _buf.ReadSize(); UpdatedAttr = new System.Collections.Generic.List<GrowthRule>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { GrowthRule _e0;  _e0 = global::cfg.GrowthRule.DeserializeGrowthRule(_buf); UpdatedAttr.Add(_e0);}}
        {int n0 = _buf.ReadSize(); UpdatedModifier = new System.Collections.Generic.List<WeaponModGrowthRule>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { WeaponModGrowthRule _e0;  _e0 = global::cfg.WeaponModGrowthRule.DeserializeWeaponModGrowthRule(_buf); UpdatedModifier.Add(_e0);}}
        ActionsGroupID = _buf.ReadInt();
        HeavyActionName = _buf.ReadString();
    }

    public static WeaponConfig DeserializeWeaponConfig(ByteBuf _buf)
    {
        return new WeaponConfig(_buf);
    }

    /// <summary>
    /// 武器ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 每级所需经验值
    /// </summary>
    public readonly System.Collections.Generic.List<float> UpdateExp;
    /// <summary>
    /// 最大等级
    /// </summary>
    public readonly int MaxLevel;
    /// <summary>
    /// 对加点的要求
    /// </summary>
    public readonly System.Collections.Generic.List<int> AbilityDemand;
    /// <summary>
    /// 基础属性
    /// </summary>
    public readonly System.Collections.Generic.List<AttrPair> BaseAttr;
    /// <summary>
    /// 基础补正
    /// </summary>
    public readonly System.Collections.Generic.List<WeaponAttrPair> BaseModifier;
    /// <summary>
    /// 升级属性增量
    /// </summary>
    public readonly System.Collections.Generic.List<GrowthRule> UpdatedAttr;
    /// <summary>
    /// 升级补正增量
    /// </summary>
    public readonly System.Collections.Generic.List<WeaponModGrowthRule> UpdatedModifier;
    /// <summary>
    /// 动作族ID
    /// </summary>
    public readonly int ActionsGroupID;
    /// <summary>
    /// 重击名称
    /// </summary>
    public readonly string HeavyActionName;
   
    public const int __ID__ = 127041694;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in BaseAttr) { _e?.ResolveRef(tables); }
        foreach (var _e in BaseModifier) { _e?.ResolveRef(tables); }
        foreach (var _e in UpdatedAttr) { _e?.ResolveRef(tables); }
        foreach (var _e in UpdatedModifier) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "UpdateExp:" + Luban.StringUtil.CollectionToString(UpdateExp) + ","
        + "MaxLevel:" + MaxLevel + ","
        + "AbilityDemand:" + Luban.StringUtil.CollectionToString(AbilityDemand) + ","
        + "BaseAttr:" + Luban.StringUtil.CollectionToString(BaseAttr) + ","
        + "BaseModifier:" + Luban.StringUtil.CollectionToString(BaseModifier) + ","
        + "UpdatedAttr:" + Luban.StringUtil.CollectionToString(UpdatedAttr) + ","
        + "UpdatedModifier:" + Luban.StringUtil.CollectionToString(UpdatedModifier) + ","
        + "ActionsGroupID:" + ActionsGroupID + ","
        + "HeavyActionName:" + HeavyActionName + ","
        + "}";
    }
}
}

