
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class WeaponEnchantmentConfig : Luban.BeanBase
{
    public WeaponEnchantmentConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        EnchantAttr = global::cfg.AttrPair.DeserializeAttrPair(_buf);
        ExpectedDuration = _buf.ReadFloat();
    }

    public static WeaponEnchantmentConfig DeserializeWeaponEnchantmentConfig(ByteBuf _buf)
    {
        return new WeaponEnchantmentConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 基础属性
    /// </summary>
    public readonly AttrPair EnchantAttr;
    /// <summary>
    /// 预期持续时间
    /// </summary>
    public readonly float ExpectedDuration;
   
    public const int __ID__ = -235714435;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        EnchantAttr?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "EnchantAttr:" + EnchantAttr + ","
        + "ExpectedDuration:" + ExpectedDuration + ","
        + "}";
    }
}
}

