
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class WeaponModGrowthRule : Luban.BeanBase
{
    public WeaponModGrowthRule(ByteBuf _buf) 
    {
        ModType = (EWeaponModifier)_buf.ReadInt();
        MinVal = _buf.ReadInt();
        MaxVal = _buf.ReadInt();
        Factor = _buf.ReadFloat();
        Constant = _buf.ReadFloat();
    }

    public static WeaponModGrowthRule DeserializeWeaponModGrowthRule(ByteBuf _buf)
    {
        return new WeaponModGrowthRule(_buf);
    }

    public readonly EWeaponModifier ModType;
    public readonly int MinVal;
    public readonly int MaxVal;
    public readonly float Factor;
    public readonly float Constant;
   
    public const int __ID__ = 657153321;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ModType:" + ModType + ","
        + "MinVal:" + MinVal + ","
        + "MaxVal:" + MaxVal + ","
        + "Factor:" + Factor + ","
        + "Constant:" + Constant + ","
        + "}";
    }
}
}

