
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class WeaponAttrPair : Luban.BeanBase
{
    public WeaponAttrPair(ByteBuf _buf) 
    {
        ModifyType = (EWeaponModifier)_buf.ReadInt();
        ModifyPercent = _buf.ReadFloat();
    }

    public static WeaponAttrPair DeserializeWeaponAttrPair(ByteBuf _buf)
    {
        return new WeaponAttrPair(_buf);
    }

    public readonly EWeaponModifier ModifyType;
    public readonly float ModifyPercent;
   
    public const int __ID__ = -1332975929;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ModifyType:" + ModifyType + ","
        + "ModifyPercent:" + ModifyPercent + ","
        + "}";
    }
}
}

